### ISSUE TITLE
Profile picture of Kairan

### ISSUE THREAD

**Issue by fabianp** [unlearning-challenge/unlearning-challenge.github.io#5]
@kairan24 : please add a picture of yourself for https://unlearning-challenge.github.io/about/

**Comment by kairanzhao** [comment]
Sure, where should I add the picture?

**Comment by fabianp** [comment]
I think assets/images looking at
https://jekyllrb.com/docs/step-by-step/07-assets/ . You might have to
create these folders

**Comment by kairanzhao** [comment]
Hi Fabian! Just sent a pull request, please review when you have time :)

**Comment by fabianp** [comment]
Merged thanks!
